pass JUPYTERHUB_README to docker-compose
bird-house/birdhouse-deploy pull request #128
Opened 2021-02-22 18:00 UTC by MatProv

Fix jupyterhub not receiving `JUPYTERHUB_README`.

`jupyterhub         |     KeyError: 'JUPYTERHUB_README'`

2021-02-22 19:31 UTC, tlvu commented
Oh that's odd, how do you get this?  That var is not supposed to be used in any template substitution yet, unless my memory is failing me.

2021-02-22 19:36 UTC, tlvu commented
It's being passed as env var to the jupyterhub container here

https://github.com/bird-house/birdhouse-deploy/blob/2b9fc6e170fef05f84154ab62afa6485fa58fc92/birdhouse/docker-compose.yml#L351-L361

So inside the jupyterhub_config.py, it should just work

https://github.com/bird-house/birdhouse-deploy/blob/2b9fc6e170fef05f84154ab62afa6485fa58fc92/birdhouse/config/jupyterhub/jupyterhub_config.py.template#L56

2021-02-22 19:57 UTC, tlvu requested changes
Just checked, we are running in prod with the PR https://github.com/bird-house/birdhouse-deploy/pull/126 that added `JUPYTERHUB_README` and we do not have any problems.

Not sure this fix is required.

2021-02-22 20:08 UTC, MatProv commented
> Not sure this fix is required.

@tlvu 
On outarde.crim.ca we had this :

`
jupyterhub         |     Traceback (most recent call last):
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2856, in launch_instance_async
jupyterhub         |         await self.initialize(argv)
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2347, in initialize
jupyterhub         |         self.load_config_file(self.config_file)
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 87, in inner
jupyterhub         |         return method(app, *args, **kwargs)
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 775, in load_config_file
jupyterhub         |         for (config, filename) in self._load_config_files(filename, path=path, log=self.log,
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 737, in _load_config_files
jupyterhub         |         config = loader.load_config()
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 616, in load_config
jupyterhub         |         self._read_file_as_dict()
jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 648, in _read_file_as_dict
jupyterhub         |         exec(compile(f.read(), conf_filename, 'exec'), namespace, namespace)
jupyterhub         |       File "/srv/jupyterhub/jupyterhub_config.py", line 56, in <module>
jupyterhub         |         readme = os.environ['JUPYTERHUB_README']
jupyterhub         |       File "/usr/lib/python3.8/os.py", line 675, in __getitem__
jupyterhub         |         raise KeyError(key) from None
jupyterhub         |     KeyError: 'JUPYTERHUB_README'
`

Once this fix has been tested on prod, jupyterhub stopped crashing.

2021-02-22 21:48 UTC, tlvu commented
> > Not sure this fix is required.
> 
> @tlvu
> On outarde.crim.ca we had this :
> 
> ```
> jupyterhub         |     Traceback (most recent call last):
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2856, in launch_instance_async
> jupyterhub         |         await self.initialize(argv)
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2347, in initialize
> jupyterhub         |         self.load_config_file(self.config_file)
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 87, in inner
> jupyterhub         |         return method(app, *args, **kwargs)
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 775, in load_config_file
> jupyterhub         |         for (config, filename) in self._load_config_files(filename, path=path, log=self.log,
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 737, in _load_config_files
> jupyterhub         |         config = loader.load_config()
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 616, in load_config
> jupyterhub         |         self._read_file_as_dict()
> jupyterhub         |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 648, in _read_file_as_dict
> jupyterhub         |         exec(compile(f.read(), conf_filename, 'exec'), namespace, namespace)
> jupyterhub         |       File "/srv/jupyterhub/jupyterhub_config.py", line 56, in <module>
> jupyterhub         |         readme = os.environ['JUPYTERHUB_README']
> jupyterhub         |       File "/usr/lib/python3.8/os.py", line 675, in __getitem__
> jupyterhub         |         raise KeyError(key) from None
> jupyterhub         |     KeyError: 'JUPYTERHUB_README'
> ```
> 
> Once this fix has been tested on prod, jupyterhub stopped crashing.

Technically this should not have happened since the new var is added as env var to the jupyterhub container.

Was the jupyterhub container re-created or just restarted?  If just restarted, then this could happen but if re-created, can not happen.  `./pavics-compose.sh up -d` will automatically re-create since the `docker-compose.yml` definition for the container changed.

I would suggest you try on `outarde` without this fix but by deleting and re-creating the jupyterhub container.

Is `outarde` on autodeploy?  What's in the logs?  autodeploy will call `./pavics-compose.sh up -d` at the end.

2021-02-22 22:03 UTC, MatProv commented
> I would suggest you try on `outarde` without this fix but by deleting and re-creating the jupyterhub container.

@tlvu For an unknown reason, outarde crashed on Friday. This morning there were only two docker containers running on the machine. After some investigation, the `pavics-compose.sh` wasn't able to reach `scheduler`, and therefore crashed within 60 seconds since docker daemon wasn't able to contact the dead container. Maybe unrelated with the JUPYTERHUB_README, pretty sure. However, this

2021-02-22 22:26 UTC, tlvu commented
> However, to fix this issue, a complete `pavics-compose.sh down` has been required. So from there, jupyterhub was completely down, before running the `pavics-compose.sh up -d`. Then, without making this variable change in the pavics-compose.sh script, jupyterhub was exiting and the logs of the container was explicitely showing the traceback. Once I added this fix, then jupyterhub stopped complaining, and was visible in canarieapi.

@MatProv 
That's not supposed to happen !

Can you:
```
./pavics-compose.sh stop jupyterhub
./pavics-compose.sh rm -v jupyterhub
git checkout -f master; git pull  # which do not have this fix, -f to make sure you do not have changed files laying around
./pavics-compose.sh up -d  # expect jupyterhub to come up without error, confirming this fix is not required
```

2021-02-23 15:33 UTC, MatProv commented
@tlvu I confirm that without the fix it works. 
I still find it strange that prod crashed the day this PR has been merged, and that the traceback explicitly mentioned `JUPYTERHUB_README`.
Well this issue is closed and doesn't have to be merged.

2021-02-23 15:33 UTC, closed without merging

2021-02-23 15:38 UTC, tlvu commented
> I still find it strange that prod crashed the day this PR has been merged, and that the traceback explicitly mentioned `JUPYTERHUB_README`.

Let's blame cosmic ray or the moon cycle :D  But seriously the fix in here is for `.template` files to perform substitution so still unrelated to the error.  I think the Docker daemon was probably due for a restart.

2021-02-23 15:48 UTC, MatProv commented
> Let's blame cosmic ray or the moon cycle :D 

Umh, haven't thought about that.. But yes, docker daemon should be considered in the potentiel root causes, since event a restart of the daemon was problematic, and I had to do it the hard way. After the last auto-deploy of this night everything looks fine on prod, so great thing.