Update canarieAPI doc links
bird-house/birdhouse-deploy pull request #139
Opened 2021-03-30 18:12 UTC by huard

- Updated components' version number. 
- Replaced links to githubio docs to readthedocs.
- renderer is provided by THREDDS-WMS. 
- slicer is provided by finch.

2021-03-30 20:02 UTC, tlvu requested changes
Use templating variable, else all good.

2021-03-30 20:17 UTC, huard commented on birdhouse/config/canarie-api/docker_configuration.py.template
> +                    'url': 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc?service=WMS&version=1.3.0&request=GetCapa
TWITCHER_PROTECTED_PATH is not used everywhere at the moment.

2021-03-30 20:18 UTC, huard commented on birdhouse/config/canarie-api/docker_configuration.py.template
> +                    'url': 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc?service=WMS&version=1.3.0&request=GetCapa
Shoud I replace `twitcher/ows/proxy` by `${TWITCHER_PROTECTED_PATH}` everywhere ?

2021-03-30 20:21 UTC, tlvu commented on birdhouse/config/canarie-api/docker_configuration.py.template
> +                    'url': 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc?service=WMS&version=1.3.0&request=GetCapa
Was introduced by Francis here https://github.com/bird-house/birdhouse-deploy/blob/fd8d811748577a52a92182682a6a30f79a35fc0b/birdhouse/env.local.example#L15 without migrating all references.

Anyways, it's still a good idea to centralize to that var and we started to use it in many places, when we touch related code, see https://github.com/bird-house/birdhouse-deploy/search?q=TWITCHER_PROTECTED_PATH

2021-03-30 20:23 UTC, tlvu commented on birdhouse/config/canarie-api/docker_configuration.py.template
> +                    'url': 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc?service=WMS&version=1.3.0&request=GetCapa
> Shoud I replace twitcher/ows/proxy by ${TWITCHER_PROTECTED_PATH} everywhere ?

Yes, careful to not introduce any typos :D

2021-03-30 20:23 UTC, tlvu commented
run tests

2021-03-31 18:09 UTC, huard commented
run tests

2021-03-31 18:28 UTC, huard commented
run tests

2021-03-31 18:49 UTC, huard commented
run tests

2021-03-31 19:01 UTC, tlvu commented
run tests

2021-03-31 19:41 UTC, tlvu approved these changes

2021-03-31 19:41 UTC, merged

2021-03-31 19:45 UTC, tlvu commented
@huard Jenkins passed https://daccs-jenkins.crim.ca/job/DACCS-iac/268/