Add notebook tools
bird-house/birdhouse-deploy pull request #97
Opened 2020-11-09 20:46 UTC by ChaamC

The google drive extension for JupyterLab requires a settings file containing the clientid of the project created in developers.google.com, which give authorization to use google drive.

This PR's role is to include this file in the birdhouse configs.

2020-11-09 20:55 UTC, dbyrns approved these changes

2020-11-09 22:55 UTC, MatProv approved these changes

2020-11-10 04:04 UTC, tlvu requested changes
Thanks for the changes.  I'd like to be defensive in case this new option is not set and I'd like to have a build with it that I can go in and try to use it, is that possible with the pipeline?  I not I'll try this manually on my side.

2020-11-10 04:07 UTC, tlvu commented
Matching PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/54 that introduced the jupyterlab-google-drive extension needing this change.

2020-11-10 18:24 UTC, MatProv commented
run tests

2020-11-10 18:30 UTC, ChaamC commented on birdhouse/config/jupyterhub/jupyterhub_config.py.template
> +c.DockerSpawner.volumes[host_gdrive_settings_path] = {
I added the proposed fix for the empty settings case!

There was no build, cause I think the build were only triggered for certain users in a whitelist. @MatProv fixed this.

We can use a different settings file depending of the environment. We will have our own settings file for 'outarde' for example, and you could have another settings file for ouranos, with a clientId for your own google project. The settings file is defined in env.local.

2020-11-10 18:53 UTC, MatProv commented
run tests

2020-11-12 01:55 UTC, tlvu commented
run tests

2020-11-13 21:22 UTC, tlvu approved these changes

2020-11-13 21:22 UTC, merged